package com.poketeammaker.enum

enum class Type {
    BUG, DARK, DRAGON,
    ELECTRIC, FAIRY, FIGHTING,
    FIRE, FLYING, GHOST,
    GRASS, GROUND, ICE,
    NORMAL, POISON, PSYCHIC,
    ROCK, STEEL, WATER;

    companion object {
        const val REG_EXP = "(BUG|DARK|DRAGON|ELECTRIC|FAIRY|FIGHTING|FIRE|FLYING|GHOST|GRASS|GROUND|ICE|NORMAL|POISON|PSYCHIC|ROCK|STEEL|WATER)"
    }
}
