package com.poketeammaker.config

import com.ulisesbocchio.jasyptspringboot.annotation.EnableEncryptableProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableEncryptableProperties
class AppConfigForJasyptStarter
